geometries/urls.py
from django.conf import settings


from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required, permission_required


# from django.conf.urls.i18n import i18n_patterns

from . import views

app_name = 'geometries'

urlpatterns = [
	# path("__admin/", admin.site.urls),

	# redirect to app's index page, if it's a sub-page
	# path('', RedirectView.as_view(url='/', permanent=True), name='kml'),

	#path('<slug:table_name>/<slug:geometry_field>/kml/', login_required(views.get_kml), name='kml'), # style as html parameter; icons in kml are references only
	#path('<slug:table_name>/<slug:geometry_field>/kmz/', login_required(views.get_kmz), name='kmz'), # kmz has icons embedded

]

if settings.REQUIRE_AUTHENTICATION:
	urlpatterns.append(path('<slug:layer_slug>/kml/', login_required(views.get_kml), name='kml')) # style as html parameter; icons in kml are references only
	urlpatterns.append(path('<slug:layer_slug>/kmz/', login_required(views.get_kmz), name='kmz')) # kmz has icons embedded
	urlpatterns.append(path('icon/<slug:layer_slug>/<slug:category_slug>/<slug:style_slug>/', login_required(views.serve_icon), name='icon')) # submid status as a slug to allow negative values, which are currently not possible using "int
else:
	urlpatterns.append(path('<slug:layer_slug>/kml/', (views.get_kml), name='kml')) # style as html parameter; icons in kml are references only
	urlpatterns.append(path('<slug:layer_slug>/kmz/', (views.get_kmz), name='kmz')) # kmz has icons embedded
	urlpatterns.append(path('icon/<slug:layer_slug>/<slug:category_slug>/<slug:style_slug>/', (views.serve_icon), name='icon')) # submid status as a slug to allow negative values, which are currently not possible using "int"

geoportal/urls.py
from django.conf import settings
from django.views.static import serve as staticserve


from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required, permission_required

from . import views


urlpatterns = [
	# admin, translations and login handling
	path('admin/', admin.site.urls), # administrate users
	path('i18n/', include('django.conf.urls.i18n')), # translations
	path('login/', views.LoginView.as_view(), name="login" ), # Login
	path('logout/', views.logout_user, name="logout" ), # Logout



	# subpages

	# webmapping
	path('map/', include('mapping.urls', namespace="map")),

	# geometry and icon source
	# TODO: separate icon into own app
	path('geometry/', include('geometries.urls', namespace="geometry")),
]


if settings.REQUIRE_AUTHENTICATION:
	urlpatterns.append(path('', login_required(RedirectView.as_view(url='map/', permanent=True)), name='index')) # index
else:
	urlpatterns.append(path('', RedirectView.as_view(url='map/', permanent=True), name='index')) # index


# The following code ensures Django will serve static files and media files with DEBUG=False turned on in settings.py (or .env). This avoids starting the development server with "--insecure" parameter
# TODO: disable the following lines when fully deploying the app with a separate webserver


if not settings.DEBUG:
	urlpatterns += [
		url(r'^media/(?P<path>.*)$', staticserve, { 'document_root': settings.MEDIA_ROOT, }),
		url(r'^static/(?P<path>.*)$', staticserve, { 'document_root': settings.STATIC_ROOT }),
	]

mapping/urls.py
from django.conf import settings
import logging
logger = logging.getLogger(__name__)

if not settings.DEBUG: logger.setLevel(settings.DEFAULT_LOG_LEVEL)
else: logger.setLevel(logging.DEBUG)

from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.views.generic.base import RedirectView
from django.contrib.auth.decorators import login_required, permission_required

# from django.conf.urls.i18n import i18n_patterns

from . import views


app_name = 'mapping'


urlpatterns = [
	# redirect to app's index page
	path('', RedirectView.as_view(url='water_supply/', permanent=True), name='map'),

	# plain map without preset layers
	path('watsan/', views.WatSanMap.as_view(), name='watsan'),
]


# register the map views.
def map_tabs():

	tabs = []

	if settings.REQUIRE_AUTHENTICATION:
		tabs.append(path('water_supply/', login_required(views.Water_Supply.as_view()), name='water_supply'),)
		tabs.append(path('sanitation/', login_required(views.Sanitation.as_view()), name='sanitation'),)
		tabs.append(path('hm_water_supply/', login_required(views.HM_Water_Supply.as_view()), name='hm_water_supply'),)
	else:
		tabs.append(path('water_supply/', views.Water_Supply.as_view(), name='water_supply'),)
		tabs.append(path('sanitation/', views.Sanitation.as_view(), name='sanitation'),)
		tabs.append(path('hm_water_supply/', views.HM_Water_Supply.as_view(), name='hm_water_supply'),)



	return tabs


urlpatterns += map_tabs()

mapping/models.py
from django.db import models

# Create your models here.

mapping/views.py
from django.conf import settings
import logging
logger = logging.getLogger(__name__)

if not settings.DEBUG: logger.setLevel(settings.DEFAULT_LOG_LEVEL)
else: logger.setLevel(logging.DEBUG)

from django.views.generic.base import View
from django.http import Http404

from django.shortcuts import render
from django.utils.translation import ugettext as _

from geometries import models
from geometries.apps import setup_db_views

from django.contrib.gis.db.models import Extent, Transform
from django.contrib.gis.db.models.functions import Transform

from datetime import datetime

from geometries.models import get_requested_model_categories_or_none
from geometries.apps import get_list_of_models_with_layer_definitions

# from geometries.views import expand_classification_to_style

from geometries.apps import get_html_parameter_or_none

from .openlayers import get_style_def_or_default
from geometries.styles import expand_classification_to_style

import json

from . import openlayers

if settings.DEBUG:
	import time



def navbar_context(self):
	"""
	The navbar is visible on all views, so some context is always required to be rendered.
	"""
	return { 'settings': settings }



def get_buffered_extents_or_empty_list(extents, absolute_buffer=0, buffer_percent=0):
	"""
	Adds spatial buffers to a given extent to not show the outer ones tied to the map boundary
	Relative buffer first, then the absolute
	"""

	if not extents or float('inf') in extents or float('-inf') in extents:
		logger.warn('Got infinite values for buffered extents!')
		return []

	relative_x = 0
	relative_y = 0

	if buffer_percent > 0:
		relative_x = (extents[2] - extents[0]) * buffer_percent/100
		relative_y = (extents[3] - extents[1]) * buffer_percent/100

	new_extents = list([
		extents[0] - (absolute_buffer + relative_x),
		extents[1] - (absolute_buffer + relative_y),
		extents[2] + (absolute_buffer + relative_x),
		extents[3] + (absolute_buffer + relative_y),
	])

	logger.debug('Buffered extents: "{}"'.format(new_extents))
	return new_extents


def get_extents_from_list_of_dict_or_empty_list(the_list, key_name):

	all_items_with_extents = [ item for item in the_list if 'extents' in item and item['extents'] ]

	extents = []

	if all_items_with_extents:
		extents = list([
			min(all_items_with_extents, key=lambda x: x['extents'][0])['extents'][0],
			min(all_items_with_extents, key=lambda x: x['extents'][1])['extents'][1],
			max(all_items_with_extents, key=lambda x: x['extents'][2])['extents'][2],
			max(all_items_with_extents, key=lambda x: x['extents'][3])['extents'][3],
		])

	if float('inf') in extents or float('-inf') in extents:
		logger.warn('Got infinite values for extents!')
		return []

	logger.debug('Got extents "{}"'.format(extents, key_name))
	return extents



class WatSanMap(View):
	"""
	This view generates all variables needed to create a webmapping and provides the elements for the side panel/legend of a webmapping page


	tables
	table			water_tanks
					water_pipes

	layers
	layer			water_tanks (geom)
					water_tanks (proposed_geom)

	categories
	category		by structure
					by age

	classifications
	classification	elevated
					ground

	styles
	style			elevated existing
					elevated proposed

	"""

	# variables modified by constructor
	template_name = 'page-webmapping.html'

	topic_layer_categories = []

	# activate this accordion by default
	topic_layer_main_feature = None


	def __init__(self, topic_layer_categories=topic_layer_categories, template_name=template_name):
		"""
		Classes inheriting from here will have to set these variables
		"""

		self.template_name = template_name
		self.topic_layer_categories = topic_layer_categories


	def get(self, request):
		"""
		Serving the user's GET request with a HTML Response
		"""

		# performance benchmarking
		if settings.DEBUG: start_time = time.time()


		# a fresh request means, layer classification might change: initiate a reload of cached layer definitions,
		# otherwise you may miss some features on the map
		for item in get_list_of_models_with_layer_definitions():
			item.layers = []
			logger.debug('LAYER reset, as DB change was initiated: "{}"'.format(item))


		# used to enrich the url parameter list with some key/value without reloading the page. This requires some JS lines in the template.
		injected_html_parameter = []

		db_has_changed = False

		# allow for a html parameter called "db" to switch the source geodatabase on-the-fly
		db = get_html_parameter_or_none(request, 'db', settings.DATABASES['geodatabase']['NAME'], expected_datatype='text', list_of_key_value_tuples=injected_html_parameter)
		#db = get_html_parameter_or_none(request, 'db', settings.DATABASES['geodatabase']['NAME'], expected_datatype='text')
		if db != settings.DATABASES['geodatabase']['NAME']:
			# On DB change, we must assume that also the meterialized views require a full setup
			setup_db_views(db=db)# vs a refresh only: setup_db_views(db=db, refresh_existing=True)
			db_has_changed = True


		# if the request was to refresh the metarialized views only; initiate it
		refresh = get_html_parameter_or_none(request, 'refresh', False, expected_datatype='boolean')
		if not db_has_changed and refresh:
			# refresh materializes views on request; if the views have not been setup anyway ...
			setup_db_views(db=db, refresh_existing=True)



		"""
		Prepare the design horizons
		"""

		design_horizon = {}

		# the set of design horizons will be populated when loading the shown layers
		set_of_design_horizons = set()

		# set an active design horizon, to be used for this mapping
		design_horizon['active'] = get_html_parameter_or_none(request, 'design_horizon', datetime.now().year, expected_datatype='integer', list_of_key_value_tuples=injected_html_parameter )
		set_of_design_horizons.add(design_horizon['active'])
		set_of_design_horizons.add(datetime.now().year)


		"""
		Picklist with the coordinate reference systems as a dict
		e.g. { 'name': 'ARC1960 UTM Z36S', 'code': 21036, 'utm': True, 'proj4_def': '+proj=utm +zone=36 +south +ellps=clrk80 +towgs84=-160,-6,-302,0,0,0,0 +units=m +no_defs'},
		"""

		crs = {}

		# get crs from settings
		try:
			crs['list'] = settings.CRS_OPTIONS

			# add FAILSAFE (= WGS84) to the list, if it's not there as it is used for the current viewport
			if not settings.FAILSAFE_CRS_OPTION in settings.CRS_OPTIONS:
				crs['list'].append(settings.FAILSAFE_CRS_OPTION)

		except:
			# do not fail here to keep page running, hoping the projection is set subsequently
			logger.warn('No entry for webmapping coordinate reference system in settings.CRS_OPTIONS = [ ... ] list. Will use settings.FAILSAFE_CRS_OPTION, ensure it is defined.')
			crs['list'] = [ settings.FAILSAFE_CRS_OPTION, ]


		# get active crs from html requst or otherwise set the active crs to the first entry in epsg list
		epsg = get_html_parameter_or_none(request, 'epsg', (crs['list'])[0]['epsg'], expected_datatype='integer', list_of_key_value_tuples=injected_html_parameter)
		crs['active'] = [ the_crs for the_crs in crs['list'] if the_crs['epsg'] == epsg ][0]
		crs['safe'] = [ the_crs for the_crs in crs['list'] if the_crs['epsg'] == settings.FAILSAFE_CRS_OPTION['epsg'] ][0]
		logger.debug('Active EPSG is {}, failsafe EPSG is {}'.format(crs['active']['epsg'], crs['safe']['epsg']))


		"""
		Determine, if Proposed and Former features should be shown
		"""

		existing_only = get_html_parameter_or_none(request, 'existing_only', False, expected_datatype='boolean', list_of_key_value_tuples=injected_html_parameter)

		"""
		Prepare the layers to show
		"""

		# Prepare list of requested layers
		requested_layer_categories = []

		# 1st: define layers that can be requested via HTML parameter:
		# layers are requested by their slug as the key, the category as it's value
		possible_models = get_list_of_models_with_layer_definitions()
		possible_layers = [ layer.the_layers(design_horizon['active']) for layer in possible_models ]


		for layer_list_of_models in list(filter(None, possible_layers)):

			# logger.info(layer_list_of_models)

			for layer_slug in [ layer['slug'] for layer in layer_list_of_models ]:

				# check if the layer is requested by testing for it's category
				category_slug = get_html_parameter_or_none(request, layer_slug, None, expected_datatype='text', list_of_key_value_tuples=injected_html_parameter )

				if category_slug:
					requested_layer_categories.append({
						'layer_slug': layer_slug,
						'category_slug': category_slug,
						'is_a_topic_layer_main_feature': False,
					})


		# 2nd: define default layers with their default categories that are always visible
		default_layer_categories = [
				{
					'layer_slug': 'administrative_boundaries_geom',
					'category_slug': 'regions',
					'is_a_topic_layer_main_feature': False,
				}
			]


		# finally, register the topic- and default layers
		for layer_category in self.topic_layer_categories + default_layer_categories:
			if not layer_category['layer_slug'] in [ already_in_list['layer_slug'] for already_in_list in requested_layer_categories ]:

				category_slug = get_html_parameter_or_none(request, layer_category['layer_slug'], layer_category['category_slug'], expected_datatype='text', list_of_key_value_tuples=injected_html_parameter )

				# logger.debug('Got category: {}'.format(category_slug))

				requested_layer_categories.append({
					'layer_slug': layer_category['layer_slug'],
					'category_slug': category_slug,
					'is_a_topic_layer_main_feature': layer_category['is_a_topic_layer_main_feature'] or False,
				})


		# at this point, we know what the user want to see on his map and how


		# topic = None
		layers = []


		"""
		layer:

		'topic': _('Water Supply'),
		'model_name': cls.__name__,
		'geometry_field': 'geom',
		'epsg': geometry_info['epsg'] if geometry_info else None,
		'dims': geometry_info['dims'] if geometry_info else None,
		'name': str(layer_name),
		'slug': slugify_javascript_var(layer_name),

templates/mapping/fragment-legend-category.html
{% load i18n %}{% load static %}


<!--
<label for="{{ layer.slug }}-category" class="sr-only">
	{{ layer.name }}
</label>
-->

{% if layer.categories|length > 1 %}

	<select
			class="form-control"
			id="{{ layer.slug }}-category"
			name="{{ layer.slug }}-category"
			size="1"
			autocomplete="off"
			data-toggle="tooltip"
			title="{{ layer.category.description }}"
		>

		{% for category_options_dict in layer.category_options %}
			<option {% if layer.category.name == category_options_dict.name %}selected{% endif %} value="{{ category_options_dict.slug }}">{{ category_options_dict.label }}</option>
		{% endfor %}

	</select>

	<script>
		document.getElementById("{{ layer.slug }}-category").onchange = function() {
			setGetParameter("{{ layer.slug }}", $(this).find(":selected").val() );
		};
	</script>

{% else %}{# single entry only: #}

	<div class="form-control" id="{{ layer.slug }}-category" name="{{ layer.slug }}-category"
		data-toggle="tooltip"
		title="{{ layer.category.description }}"
		>{{ layer.category.label }}</div>

{% endif %}

templates/mapping/fragment-legend-classification.html
{% load i18n %}

{% for classification in classifications %}
	{% include 'mapping/fragment-legend-style.html' with styles=classification.styles map=map %}
{% endfor %}

templates/mapping/fragment-legend-layer.html
{% load i18n %}

{% comment %}



{% endcomment %}



<div class="my-0 p-1 flex-column align-items-start alert alert-secondary"
>

	<div class="d-flex w-100 justify-content-between m-0 p-0">

		<div>

			<!-- layer name -->
			<span class="font-weight-bold" data-toggle="tooltip" title="{{ layer.description|safe }}">
				{{ layer.label }}
			</span>


			<!-- Vector download button -->
			{% if not settings.DEBUG %}

				<small>
					<a class="badge badge-secondary" href="{% url 'geometry:kmz' layer_slug=layer.slug %}
						?category={{ layer.category.slug }}&design_horizon={{ design_horizon.active }}&existing_only={{ existing_only }}"
						data-toggle="tooltip"
						title="{% trans 'Download KMZ' %}"
					>KMZ</a>
				</small>

			{% else %}

				<small>
					<a class="badge badge-primary"
						href="{% url 'geometry:kml' layer_slug=layer.slug %}
						?category={{ layer.category.slug }}&design_horizon={{ design_horizon.active }}&existing_only={{ existing_only }}"
						data-toggle="tooltip"
						title="{% trans 'Download KML' %}"
					>KML</a>
				</small>

			{% endif %}

		</div>

		<!-- Category picklist for this layer -->
		<div>
			{% include "mapping/fragment-legend-category.html" %}
		</div>

	</div>

	{# <div class="d-flex w-100 justify-content-between mb-1"> #} {# overflow-auto would make sense here #}
	<div class="w-100 my-1 p-0">
		{% comment %}
			Include the classifications with their styles
		{% endcomment %}

		{% include "mapping/fragment-legend-classification.html" with classifications=layer.category.classifications map=map %}

	</div>

</div>


<script>

	var {{ layer.slug }}_kml = new ol.layer.Vector({
		source: new ol.source.Vector({
			url: "{% url 'geometry:kml' layer_slug=layer.slug %}?category={{ layer.category.slug }}&existing_only={{ existing_only }}&design_horizon={{ design_horizon.active }}",
			format: new ol.format.KML({ extractStyles: false, }),
			crossOrigin: "anonymous",
		})
		, style: function(feature) {

			this_style = feature.get('styleUrl');

			{# strange: only for the 'styleURL' field, the response of feature.get includes the rest of the URL, not just the field value (other KML fields work!) #}
			{# as a workaround, a string operation extracts the style id by cutting of the rest #}
			this_style = '#' + this_style.split("#").pop();

			switch(this_style) {
				{% for classification in layer.category.classifications %}
					{% for style in classification.styles %}
						case '#{{ style.slug }}':
							if ({{ style.slug }}.getText()) {
								{{ style.slug }}.getText().setText(feature.get('name'));
							}
							return {{ style.slug }};
					{% endfor %}
				{% endfor %}
			}

		}
		/*
		, style: function(feature) {
					LabelStyle.ugettext().setText(feature.get('name'));
					return LabelStyle;
				}
		*/
		, declutter: false
		{% if layer.category.min_scale %}, minResolution: {% if crs.active.utm %}{{ layer.category.min_scale }}{% else %}{{ layer.category.min_scale }} / {{ settings.WGS84_TO_UTM_SCALE_FACTOR }}{% endif %}{% endif %}
		{% if layer.category.max_scale %}, maxResolution: {% if crs.active.utm %}{{ layer.category.max_scale }}{% else %}{{ layer.category.max_scale }} / {{ settings.WGS84_TO_UTM_SCALE_FACTOR }}{% endif %}{% endif %}
	});


	{# FIXME: Quick layer order from front to back: point -> line -> polygon #}
	{{ layer.slug }}_kml.setZIndex( (-1 * {{ layer.dims }}) + 10 || 0);

	map.addLayer({{ layer.slug }}_kml);

</script>

templates/mapping/fragment-legend-style.html
{% load i18n %}{% load static %}


{% for style in styles %}

	<script>
		{{ style.var_ol_style|safe }}
	</script>

	<button type="button" class="btn align-self-center m-0 p-0" data-toggle="tooltip"

		{% if style.extents %}
			onclick="{{ map }}.getView().fit( ol.proj.transformExtent( {{ style.extents }}, 'EPSG:{{ layer.epsg }}', 'EPSG:{{ crs.active.epsg }}' ) );"
			title="{{ style.label }}<br>
			{% if style.description %}{{ style.description }}{% endif %}"
		{% else %}
			title="{{ style.label }}<br>
			{% if style.description %}{{ style.description }}{% endif %}"
		{% endif %}
		>

		<span class="badge badge-light m-0 p-0">
			<img src="{% url 'geometry:icon' layer_slug=layer.slug category_slug=layer.category.slug style_slug=style.slug %}"
				width="{{ settings.GUI_ICON_SIZE_PX }}px"
				height="{{ settings.GUI_ICON_SIZE_PX }}px"
				alt="Style symbol"
			/>
			<span style='color:{{ style.base_color }}'>{{ style.number_of_features }}</span>
		</span>

	</button>

{% endfor %}

templates/mapping/fragment-map-tabs.html
{% load i18n %}
{% load static %}

<ul class="nav nav-tabs justify-content-between">


	{# FIXME: real reverse for url using templatetag #}

	{% for tab in tabs.list %}
		<li class="nav-item">
			<a class="nav-link{% if forloop.counter == tabs.active %} active{% endif %}{% if tab.disabled %} disabled{% endif %}" href="{{ tab.href }}">{{ tab.topic }}{% if forloop.counter == tab.active %} {{ design_horizon }}{% endif %}</a>
		</li>
	{% endfor %}

	<!--
	<li class="nav-item">
		<a class="nav-link {% if active == 2 %}active{% endif %}" href="/sanitation/">{% trans "Sanitation" %} {{ design_horizon }}</a>
	</li>

	<li class="nav-item">
		<a class="nav-link disabled {% if active == 3 %}active{% endif %}" href="/map/">{% trans "Incidents" %}</a>
	</li>

	<li class="nav-item">
		<a class="nav-link disabled {% if active == 4 %}active{% endif %}" href="/map/">{% trans "Hydraulic modelling" %}</a>
	</li>
	-->

	<li class="nav-item ml-auto m-0 p-0">
		{# right content #}

		<span class="navbar-text m-0 p-0">
			<button type="button" class="form-control m-0 p-1 btn btn-sm btn-outline-secondary"
				id="initiate_refresh" name="initiate_refresh" data-toggle="tooltip"
				title="{% trans 'Initiate a manual refresh of the map; e.g. if you know the GIS content has changed, but is not shown here.' %}">
				{% trans 'Refresh' %}
			</button>
			<script>
				document.getElementById('initiate_refresh').onclick = function() {
					setGetParameter('refresh', true );
				};
			</script>
		</span>


		<span class="navbar-text m-0 p-0">
			<select class="form-control m-0 p-1" id="design_horizon_picklist" autocomplete="off" name="design_horizon" size="1" data-toggle="tooltip"
				title="{% trans 'Style map features considering this design horizon.' %} {% trans 'Infrastructure with \"InstallationDate\" later then {{  }} will be styled as proposed.' %}" >
				{% for the_design_horizon in design_horizon.list %}
					<option {% if the_design_horizon == design_horizon.active %}selected{% endif %} value="{{ the_design_horizon }}" >{{ the_design_horizon }}</option>
				{% endfor %}
			</select>
			<script>
				document.getElementById('design_horizon_picklist').onchange = function() {
					wert = document.getElementById("design_horizon_picklist").value;
					setGetParameter('design_horizon', wert );
				};
			</script>
		</span>


		<span class="navbar-text m-0 p-0">
			<div class="form-check">
				<input {% if existing_only %}checked {% endif %}class="form-check-input" type="checkbox" value="" id="existing_only_checkbox" data-toggle="tooltip"
					title="{% trans 'Show only features that are existing in the requested design horizon' %}  ({{ design_horizon.active }}). {% trans 'Will otherwise show proposed and decommissioned features as well.' %} ">
				<label class="form-check-label" for="defaultCheck1">
					{% trans 'Existing only' %}
				</label>
			</div>
			<script>
				document.getElementById('existing_only_checkbox').onchange = function() {
					wert = document.getElementById("existing_only_checkbox").checked;
					setGetParameter('existing_only', wert );
				};
			</script>
		</span>


		<span class="navbar-text m-0 p-0">
			<select class="form-control m-0 p-1" id="crs_picklist" autocomplete="off" name="crs_picklist" size="1" data-toggle="tooltip" title="{% trans 'Coordinate reference system for map' %}" >
				{% for the_crs in crs.list %}
					<option {% if the_crs.epsg == crs.active.epsg %}selected{% endif %} value="{{ the_crs.epsg }}">{{ the_crs.name }}</option>
				{% endfor %}
			</select>
			<script>
				document.getElementById('crs_picklist').onchange = function() {
					wert = document.getElementById("crs_picklist").value;
					setGetParameter('epsg', wert );
				};
			</script>
		</span>

		<span class="navbar-text m-0 p-0">

			<small>
			<button id="export-to-pdf" class="btn btn-sm btn-outline-secondary mx-0 my-0">
				<img src='{% static "icons/gui/print.svg" %}' height="18px" data-toggle="tooltip" title="{% trans 'Printable map' %}";/>
			</button>

			{# <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.debug.js" integrity="sha384-NaWTHo/8YCBYJ59830LTz/P4aQZK1sS0SneOgAvhsIl3zBu8r9RevNg5lHCHAuQ/" crossorigin="anonymous"></script> #}
			{# <script src="{% static 'js/print_button_jspdf.js' %}" crossorigin="anonymous"></script> #}

			</small>

		</span>
	</li>


</ul>